import { GiCommercialAirplane } from "react-icons/gi";
import { PiChairFill } from "react-icons/pi";
import { FaCar } from "react-icons/fa";
import { FaUmbrellaBeach } from "react-icons/fa";
import photo1 from "../assets/photo1.jpg";
import photo2 from "../assets/photo2.jpg";

export const travelArr = [
  {
    icon: GiCommercialAirplane,
    title: "Города",
  },
  {
    icon: PiChairFill,
    title: "Океан",
  },
  {
    icon: FaCar,
    title: "Горы",
  },
  {
    icon: PiChairFill,
    title: "Пребывание",
  },
  {
    icon: PiChairFill,
    title: "Пребывание",
  },
  {
    icon: FaCar,
    title: "Пребывание",
  },
  {
    icon: FaCar,
    title: "Машины",
  },
  {
    icon: FaCar,
    title: "Машины",
  },
  {
    icon: FaCar,
    title: "Машины",
  },
  {
    icon: FaUmbrellaBeach,
    title: "Пакеты",
  },
];

export const travelData = [
  {
    image: photo1,
    rating: "4.7",
    city: "Paris",
    country: "France",
    price: "$800",
    type: "Города",
    when: "2 августа, сб - 8 августа, пт",
    about: "1 ч, без пересадок",
  },
  {
    image: photo2,
    rating: "4.7",
    city: "Paris",
    country: "France",
    price: "$800",
    type: "Города",
    when: "2 августа, сб - 8 августа, пт",
    about: "1 ч, без пересадок",
  },
  {
    image: photo1,
    rating: "4.7",
    city: "Paris",
    country: "France",
    price: "$800",
    type: "Города",
    when: "2 августа, сб - 8 августа, пт",
    about: "1 ч, без пересадок",
  },
  {
    image: photo1,
    rating: "4.7",
    city: "Paris",
    country: "France",
    price: "$800",
    type: "Города",
    when: "2 августа, сб - 8 августа, пт",
    about: "1 ч, без пересадок",
  },
  {
    image: photo1,
    rating: "4.7",
    city: "Paris",
    country: "France",
    price: "$800",
    type: "Города",
    when: "2 августа, сб - 8 августа, пт",
    about: "1 ч, без пересадок",
  },
  {
    image: photo2,
    rating: "4.7",
    city: "Paris",
    country: "France",
    price: "$800",
    type: "Города",
    when: "2 августа, сб - 8 августа, пт",
    about: "1 ч, без пересадок",
  },
  {
    image: photo1,
    rating: "4.7",
    city: "Paris",
    country: "France",
    price: "$800",
    type: "Города",
    when: "2 августа, сб - 8 августа, пт",
    about: "1 ч, без пересадок",
  },
  {
    image: photo1,
    rating: "4.7",
    city: "Paris",
    country: "France",
    price: "$800",
    type: "Города",
    when: "2 августа, сб - 8 августа, пт",
    about: "1 ч, без пересадок",
  },
  {
    image: photo2,
    rating: "4.7",
    city: "Pacific Ocean",
    country: "Ocean",
    price: "$500",
    type: "Океан",

    when: "2 августа, сб - 8 августа, пт",
    about: "1 ч, без пересадок",
  },
  {
    image: photo2,
    rating: "4.7",
    city: "Pacific Ocean",
    country: "Ocean",
    price: "$500",
    type: "Океан",
    when: "2 августа, сб - 8 августа, пт",
    about: "1 ч, без пересадок",
  },
  {
    image: photo2,
    rating: "4.7",
    city: "Pacific Ocean",
    country: "Ocean",
    price: "$500",
    type: "Океан",

    when: "2 августа, сб - 8 августа, пт",
    about: "1 ч, без пересадок",
  },
  {
    image: photo2,
    rating: "4.7",
    city: "Pacific Ocean",
    country: "Ocean",
    price: "$500",
    type: "Океан",

    when: "2 августа, сб - 8 августа, пт",
    about: "1 ч, без пересадок",
  },
  {
    image: photo2,
    rating: "4.7",
    city: "Pacific Ocean",
    country: "Ocean",
    price: "$500",
    type: "Горы",

    when: "2 августа, сб - 8 августа, пт",
    about: "1 ч, без пересадок",
  },
  {
    image: photo2,
    rating: "4.7",
    city: "Pacific Ocean",
    country: "Ocean",
    price: "$500",
    type: "Горы",

    when: "2 августа, сб - 8 августа, пт",
    about: "1 ч, без пересадок",
  },
  {
    image: photo2,
    rating: "4.7",
    city: "Pacific Ocean",
    country: "Ocean",
    price: "$500",
    type: "Горы",

    when: "2 августа, сб - 8 августа, пт",
    about: "1 ч, без пересадок",
  },
  {
    image: photo2,
    rating: "4.7",
    city: "Pacific Ocean",
    country: "Ocean",
    price: "$500",
    type: "Машины",
    when: "2 августа, сб - 8 августа, пт",
    about: "1 ч, без пересадок",
  },
  {
    image: photo1,
    rating: "4.7",
    city: "Pacific Ocean",
    country: "Ocean",
    price: "$500",
    type: "Пребывание",
    when: "2 августа, сб - 8 августа, пт",
    about: "1 ч, без пересадок",
  },
  {
    image: photo2,
    rating: "4.7",
    city: "Pacific Ocean",
    country: "Ocean",
    price: "$500",
    type: "Пребывание",
    when: "2 августа, сб - 8 августа, пт",
    about: "1 ч, без пересадок",
  },
  {
    image: photo1,
    rating: "4.7",
    city: "Pacific Ocean",
    country: "Ocean",
    price: "$500",
    type: "Пакеты",
    when: "2 августа, сб - 8 августа, пт",
    about: "1 ч, без пересадок",
  },
];
