export const vacArr = [
  {
    position: "Проектный менеджер",
    where: "Kyrgyz Сoncept",
    info: "Удалённо",
    date: "13 июль, 2025",
    info2: "Полная занятость",
    skills: "JIRA",
    skills2: "Asana",
    skills3: "Trello",
  },
  {
    position: "Проектный менеджер",
    where: "Kyrgyz Сoncept",
    info: "Удалённо",
    date: "13 июль, 2025",
    info2: "Полная занятость",
    skills: "JIRA",
    skills2: "Asana",
    skills3: "Trello",
  },
  {
    position: "Проектный менеджер",
    where: "Kyrgyz Сoncept",
    info: "Удалённо",
    date: "13 июль, 2025",
    info2: "Полная занятость",
    skills: "JIRA",
    skills2: "Asana",
    skills3: "Trello",
  },
  {
    position: "Проектный менеджер",
    where: "Kyrgyz Сoncept",
    info: "Удалённо",
    date: "13 июль, 2025",
    info2: "Полная занятость",
    skills: "JIRA",
    skills2: "Asana",
    skills3: "Trello",
  },
  {
    position: "Проектный менеджер",
    where: "Kyrgyz Сoncept",
    info: "Удалённо",
    date: "13 июль, 2025",
    info2: "Полная занятость",
    skills: "JIRA",
    skills2: "Asana",
    skills3: "Trello",
  },
  {
    position: "Проектный менеджер",
    where: "Kyrgyz Сoncept",
    info: "Удалённо",
    date: "13 июль, 2025",
    info2: "Полная занятость",
    skills: "JIRA",
    skills2: "Asana",
    skills3: "Trello",
  },
];
